name: Build and Deploy Code

on: [push, pull_request]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repository
        uses: actions/checkout@v3
      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: upgrade pip
        run: pythong -m pip install --upgrade pip
      - name: install all dependencies
        run: pip install -r requirements.txt
